/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/lucbettaieb/ros_workspace/cwru_base_hydro/catkin/src/cwru_base/msg/cRIOSensors.msg
 *
 */


#ifndef CWRU_BASE_MESSAGE_CRIOSENSORS_H
#define CWRU_BASE_MESSAGE_CRIOSENSORS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace cwru_base
{
template <class ContainerAllocator>
struct cRIOSensors_
{
  typedef cRIOSensors_<ContainerAllocator> Type;

  cRIOSensors_()
    : header()
    , left_wheel_encoder(0)
    , right_wheel_encoder(0)
    , left_motor_encoder(0)
    , right_motor_encoder(0)
    , yaw_rate(0)
    , yaw_temp(0)
    , yaw_ref(0)  {
    }
  cRIOSensors_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left_wheel_encoder(0)
    , right_wheel_encoder(0)
    , left_motor_encoder(0)
    , right_motor_encoder(0)
    , yaw_rate(0)
    , yaw_temp(0)
    , yaw_ref(0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _left_wheel_encoder_type;
  _left_wheel_encoder_type left_wheel_encoder;

   typedef int32_t _right_wheel_encoder_type;
  _right_wheel_encoder_type right_wheel_encoder;

   typedef int32_t _left_motor_encoder_type;
  _left_motor_encoder_type left_motor_encoder;

   typedef int32_t _right_motor_encoder_type;
  _right_motor_encoder_type right_motor_encoder;

   typedef int16_t _yaw_rate_type;
  _yaw_rate_type yaw_rate;

   typedef int16_t _yaw_temp_type;
  _yaw_temp_type yaw_temp;

   typedef int16_t _yaw_ref_type;
  _yaw_ref_type yaw_ref;




  typedef boost::shared_ptr< ::cwru_base::cRIOSensors_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cwru_base::cRIOSensors_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct cRIOSensors_

typedef ::cwru_base::cRIOSensors_<std::allocator<void> > cRIOSensors;

typedef boost::shared_ptr< ::cwru_base::cRIOSensors > cRIOSensorsPtr;
typedef boost::shared_ptr< ::cwru_base::cRIOSensors const> cRIOSensorsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cwru_base::cRIOSensors_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cwru_base::cRIOSensors_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cwru_base

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'cwru_base': ['/home/lucbettaieb/ros_workspace/cwru_base_hydro/catkin/src/cwru_base/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cwru_base::cRIOSensors_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cwru_base::cRIOSensors_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cwru_base::cRIOSensors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cwru_base::cRIOSensors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cwru_base::cRIOSensors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cwru_base::cRIOSensors_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cwru_base::cRIOSensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "210acf44f8ca85255cab84f619fb4f26";
  }

  static const char* value(const ::cwru_base::cRIOSensors_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x210acf44f8ca8525ULL;
  static const uint64_t static_value2 = 0x5cab84f619fb4f26ULL;
};

template<class ContainerAllocator>
struct DataType< ::cwru_base::cRIOSensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cwru_base/cRIOSensors";
  }

  static const char* value(const ::cwru_base::cRIOSensors_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cwru_base::cRIOSensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int32 left_wheel_encoder\n\
int32 right_wheel_encoder\n\
int32 left_motor_encoder\n\
int32 right_motor_encoder\n\
\n\
int16 yaw_rate\n\
int16 yaw_temp\n\
int16 yaw_ref\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::cwru_base::cRIOSensors_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cwru_base::cRIOSensors_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left_wheel_encoder);
      stream.next(m.right_wheel_encoder);
      stream.next(m.left_motor_encoder);
      stream.next(m.right_motor_encoder);
      stream.next(m.yaw_rate);
      stream.next(m.yaw_temp);
      stream.next(m.yaw_ref);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct cRIOSensors_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cwru_base::cRIOSensors_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cwru_base::cRIOSensors_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left_wheel_encoder: ";
    Printer<int32_t>::stream(s, indent + "  ", v.left_wheel_encoder);
    s << indent << "right_wheel_encoder: ";
    Printer<int32_t>::stream(s, indent + "  ", v.right_wheel_encoder);
    s << indent << "left_motor_encoder: ";
    Printer<int32_t>::stream(s, indent + "  ", v.left_motor_encoder);
    s << indent << "right_motor_encoder: ";
    Printer<int32_t>::stream(s, indent + "  ", v.right_motor_encoder);
    s << indent << "yaw_rate: ";
    Printer<int16_t>::stream(s, indent + "  ", v.yaw_rate);
    s << indent << "yaw_temp: ";
    Printer<int16_t>::stream(s, indent + "  ", v.yaw_temp);
    s << indent << "yaw_ref: ";
    Printer<int16_t>::stream(s, indent + "  ", v.yaw_ref);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CWRU_BASE_MESSAGE_CRIOSENSORS_H
